FROM python:3.8

ENV APP_ROOT /app
RUN mkdir ${APP_ROOT}
RUN apt-get update
RUN apt-get install ffmpeg libsm6 libxext6  -y
WORKDIR ${APP_ROOT}
COPY requirements.txt .
RUN pip install --upgrade pip \
  && pip install -r requirements.txt \
  # && pip install alembic #igonre alembic