// Generated by https://quicktype.io

export interface StockProduct {
  Product: Product;
}

export interface Product {
  id: string;
  uuid: string;
  brand: Brand;
  condition: string;
  countryOfManufacture: string;
  gender: string;
  contentGroup: string;
  minimumBid: number;
  name: string;
  primaryCategory: Brand;
  secondaryCategory: Brand;
  usHtsCode: string;
  usHtsDescription: string;
  productCategory: Brand;
  releaseDate: string;
  shoe: string;
  shortDescription: string;
  tickerSymbol: string;
  title: Brand;
  dataType: string;
  urlKey: string;
  sizeLocale: string;
  sizeTitle: string;
  sizeDescriptor: string;
  sizeAllDescriptor: string;
  description: string;
  lithiumIonBattery: boolean;
  hazardousMaterial: null;
  type: boolean;
  aLim: number;
  year: number;
  shippingGroup: Brand;
  traits: Trait[];
  meta: Meta;
  PortfolioItems: any[];
  shipping: Shipping;
  enhancedImage: EnhancedImage;
  media: Media;
  charityCondition: number;
  breadcrumbs: Breadcrumb[];
  market: EnhancedImage;
  children?: { [key: string]: Product };
  parentId?: string;
  parentUuid?: string;
  shoeSize?: string;
  sizeSortOrder?: number;
  skuVariantGroup?: null;
}

export enum Brand {
  Home = "Home",
  OtherBrands = "Other Brands",
  Streetwear = "streetwear",
  Stussy = "Stussy",
  StussyContrastStitchLabelCrewNavy = "Stussy Contrast Stitch Label Crew Navy",
}

export interface Breadcrumb {
  level: number;
  name: Brand;
  url: URL;
}

export enum URL {
  Empty = "/",
  OtherStreetwear = "/other-streetwear",
  OtherStreetwearStussy = "/other-streetwear/stussy",
  Streetwear = "/streetwear",
  StussyContrastStitchLabelCrewNavy = "/stussy-contrast-stitch-label-crew-navy",
}

export interface EnhancedImage {}

export interface Media {
  "360": any[];
  imageUrl: string;
  smallImageUrl: string;
  thumbUrl: string;
  has360: boolean;
  gallery: string[];
}

export interface Meta {
  charity: boolean;
  raffle: boolean;
  mobile_only: boolean;
  restock: boolean;
  deleted: boolean;
  hidden: boolean;
  lock_buying: boolean;
  lock_selling: boolean;
  redirected: boolean;
  browse_page_featured: boolean;
}

export interface Shipping {
  totalDaysToShip: number;
  hasAdditionalDaysToShip: boolean;
  deliveryDaysLowerBound: number;
  deliveryDaysUpperBound: number;
}

export interface Trait {
  name: Name;
  key: Key;
  value: boolean | number | string;
  filterable: boolean;
  visible: boolean;
  highlight: boolean;
  format?: Format;
}

export enum Format {
  Currency = "currency",
  Date = "date",
}

export enum Key {
  Colorway = "colorway",
  Featured = "featured",
  ReleaseDate = "release_date",
  RetailPrice = "retail_price",
  Season = "season",
}

export enum Name {
  Color = "Color",
  Featured = "Featured",
  ReleaseDate = "Release Date",
  Retail = "Retail",
  Season = "Season",
}
