FROM node:16.13.0
# add chrome repo
RUN echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list
RUN curl https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN apt-get update
# install googgle chrome
RUN apt-get update && apt-get install -y google-chrome-stable
ENV APP_ROOT /app
RUN mkdir ${APP_ROOT}
WORKDIR ${APP_ROOT}
COPY package.json .
RUN npm install
